#!/bin/bash

echo
echo please choose anyone.
echo
echo 'a = Display Date and time'
echo 'b = show current directory'
echo 'c= shows list logged in'
echo 
	read choices
	case $choices in
a) date;;
b) pwd;;
c) who;;
*) echo choose valid option
	esac
