#!/bin/bash

#Description: this script will find directories without users

cd /home
for dir in *
do 
	check=$(grep -c "/home/$dir" /etc/passwd)
	if [ $check -ge 1 ]
	then
	echo "$dir is assingned to user"
	else
	echo "$dir is not assigned to user" 
	fi
done
